version: "3.7"
services:
  mongodb:
    hostname: easytravel-mongodb
    container_name: mongodb
    image: "dynatrace/easytravel-mongodb"
    ports:
      - 27017
      - 28017

  backend:
    hostname: easytravel-backend
    container_name: backend
    image: "dynatrace/easytravel-backend"
    ports:
      - 8080
    links:
      - mongodb
    volumes_from:
      - dtagent
    external_links:
      - dtserver
    environment:
      CATALINA_OPTS: "-agentpath:/dynatrace/agent/lib64/libdtagent.so=name=BusinessBackend_easyTravel,collector=docker-dtserver"
      ET_DATABASE_LOCATION: "easytravel-mongodb:27017"
      ET_MONGO_AUTH_DB: "admin"
      ET_DATABASE_USER: "etAdmin"
      ET_DATABASE_PASSWORD: "adminadmin"

  frontend:
    hostname: easytravel-frontend
    container_name: frontend
    image: "dynatrace/easytravel-frontend"
    ports:
      - 8080
    links:
      - backend
      - mongodb
    volumes_from:
      - dtagent
    external_links:
      - dtserver
    environment:
      CATALINA_OPTS: "-agentpath:/dynatrace/agent/lib64/libdtagent.so=name=CustomerFrontend_easyTravel,collector=docker-dtserver"
      ET_BACKEND_URL: "http://easytravel-backend:8080"

  www:
    hostname: easytravel-www
    container_name: www
    image: "dynatrace/easytravel-nginx"
    ports:
      - 80
    links:
      - frontend
      - backend
    volumes_from:
      - dtagent
    external_links:
      - dtserver
    environment:
      ET_FRONTEND_LOCATION: "easytravel-frontend:8080"
      ET_BACKEND_LOCATION: "easytravel-backend:8080"
      DT_AGENT_NAME: "WebServer_easyTravel"
      DT_AGENT_COLLECTOR: "dtserver"
      LD_PRELOAD: "/dynatrace/agent/lib64/libdtagent.so"
    command: sh -c "/dynatrace/run-wsagent.sh && /run-process.sh"

  loadgen:
    container_name: loadgen
    image: "dynatrace/easytravel-loadgen"
    links:
      - backend
      - frontend
      - www
    environment:
      ET_FRONTEND_URL: "http://easytravel-www:80"
      ET_BACKEND_URL: "http://easytravel-www:8080"
      ET_PROBLEMS: "BadCacheSynchronization,CPULoad,DatabaseCleanup,DatabaseSlowdown,FetchSizeTooSmall,JourneySearchError404,JourneySearchError500,LoginProblems,MobileErrors,TravellersOptionBox"
